import PropTypes from "prop-types";

const PatientBasicData = PropTypes.shape({
  patient_id: PropTypes.number.isRequired,
  reason_of_report: PropTypes.string,
  major_ailments: PropTypes.string,
  suicidal_thoughts_choice: PropTypes.number,
  suicidal_thoughts: PropTypes.string,
  other_ailments: PropTypes.string,
  past_diseases_choice: PropTypes.string,
  past_diseases: PropTypes.string,
  past_psychiatric_treatment: PropTypes.number,
  first_hospitalization: PropTypes.string,
  hospitalization_times: PropTypes.number,
  pharmacotherapy: PropTypes.string,
  psychotherapy: PropTypes.string,
  family_therapy: PropTypes.string,
  medications_used: PropTypes.string,
  allergies: PropTypes.string,
  hygiene: PropTypes.string,
  education_choice: PropTypes.string,
  education: PropTypes.string,
  professional_status: PropTypes.string,
  social_conditions: PropTypes.string,
  social_assistance_choice: PropTypes.number,
  social_assistance: PropTypes.string,
  social_level_changes: PropTypes.string,
  development_data: PropTypes.string,
  family_situation: PropTypes.string,
  family_situation_changes: PropTypes.string,
  family_relationships: PropTypes.string,
  hereditary_taint: PropTypes.string,
  physical_activity: PropTypes.string,
  self_mutilation: PropTypes.string,
  occupational_exposure: PropTypes.string,
  alcohol: PropTypes.string,
  nicotine: PropTypes.string,
  psychoactive_substances: PropTypes.string,
  diet_choice: PropTypes.string,
  diet: PropTypes.string,
  family_interview: PropTypes.string,
});

export default PatientBasicData;
