import PropTypes from "prop-types";

const PatientPhysicalExamination = PropTypes.shape({
  patient_id: PropTypes.number.isRequired,
  general_conditions: PropTypes.string.isRequired,
  blood_pressure: PropTypes.string,
  pulse: PropTypes.string,
  body_temperature: PropTypes.string,
  body_build_type: PropTypes.string.isRequired,
  skin_appearance: PropTypes.string,
  skin_colour: PropTypes.string,
  skin_humidity: PropTypes.string,
  skin_swelling: PropTypes.string,
  skin_scars: PropTypes.string,
  lymphatic_gland_examined: PropTypes.bool.isRequired,
  head_appearance_choice: PropTypes.bool,
  head_appearance: PropTypes.string,
  head_percussion_tenderness: PropTypes.string,
  head_eyeballs: PropTypes.string,
  ears: PropTypes.string,
  nose: PropTypes.string,
  mouth_teeth: PropTypes.string.isRequired,
  mucous_membrane_choice: PropTypes.string,
  mucous_membrane: PropTypes.string,
  neck_throat_tonsil: PropTypes.string,
  neck_appearance: PropTypes.string,
  neck_thyroid_choice: PropTypes.string,
  neck_thyroid: PropTypes.string,
  chest_choice: PropTypes.string,
  chest: PropTypes.string,
  breath_frequency: PropTypes.string,
  chest_percussion_choice: PropTypes.string,
  chest_percussion: PropTypes.string,
  chest_auscultation_choice: PropTypes.bool,
  chest_auscultation: PropTypes.string,
  cardiovascular_appearance: PropTypes.string,
  cardiovascular_efficient: PropTypes.string,
  cardiovascular_auscultation: PropTypes.string,
  cardiovascular_pulse_choice: PropTypes.bool,
  cardiovascular_pulse: PropTypes.string,
  stomach: PropTypes.string,
  stomach_hernia: PropTypes.string,
  stomach_painless: PropTypes.string,
  stomach_auscultation: PropTypes.string,
  stomach_percussion: PropTypes.string,
  stomach_physical_examination: PropTypes.string,
  stomach_symptoms: PropTypes.string,
  legs_swelling: PropTypes.string,
  legs_veins: PropTypes.string,
  locomotor_joint_outline: PropTypes.bool.isRequired,
  locomotor_limb_mobility: PropTypes.bool.isRequired,
  muscle_strength_tension: PropTypes.bool.isRequired,
  nervous_meningeal_signs: PropTypes.string,
  nervous_focal_damage: PropTypes.string,
});

export default PatientPhysicalExamination;
